### ISSUE TITLE
thank you for omni to org converter 

### ISSUE THREAD

**Issue by jtangpublic** [jeapostrophe/exp#3]
I'm so happy to see an Omni Focus to Org converter.  I have all my important records in Omni Outliner. Do you know anyone who would be able and willing to write an Omni Outliner to Org converter?

**Comment by jeapostrophe** [comment]
Sorry, I don't know anything about that format, but I seem to recall that when I wrote this code (7 years ago!) OmniFocus files had pieces that were identical to OmniOutliner files, so I wouldn't be surprised if it were "easy" to convert them.

**Comment by jtangpublic** [comment]
Okay, I will see if I can find someone else who would be able to do it.
Thanks!
Joyce
